import {
  react,
  git,
  express,
  css,
  html,
  js,
  mongo,
  country,
  crypto,
  ricky,
  shop,
  translate,
  resort,
  tailwind,
  reactrouter,
} from "../assets/index";
export const tages = [
  "Reactjs",
  "Git",
  "Expressjs",
  "Css",
  "Html",
  "Javascript",
  "Mongodb",
  "TailwindCss",
  "React-Router",
];
export const Images = [
  react,
  git,
  express,
  css,
  html,
  js,
  mongo,
  tailwind,
  reactrouter,
];
export const Projects = [
  {
    image: country,
    desc: "A web application that provides information about countries around the world.",
    demo: "https://saladilakshman.github.io/country-app/",
    code: "https://github.com/saladilakshman/country-app",
  },
  {
    image: crypto,
    desc: "A web application that provides cryptocurrency market statistics and trending crypto-related news",
    demo: "https://saladilakshman.github.io/cryptolist/",
    code: "https://github.com/saladilakshman/cryptolist",
  },
  {
    image: ricky,
    desc: 'A web application that provides information about the characters from the animated TV series "Rick and Morty".',
    demo: "https://saladilakshman.github.io/rickymorty/",
    code: "https://github.com/saladilakshman/rickymorty",
  },
  {
    image: shop,
    desc: "A web application for a Eye Glasses E-Commerce App to explore various glasswears for eye",
    demo: "https://saladilakshman.github.io/shopping-app/",
    code: "https://github.com/saladilakshman/shopping-app",
  },
  {
    image: translate,
    desc: "Google Web-translator, whcih translates texts to various languages supported by google and can copy the text too ",
    demo: "https://saladilakshman.github.io/translator-app/",
    code: "https://github.com/saladilakshman/translator-app",
  },
  {
    image: resort,
    desc: "Beach resort website, allowing users to explore available rooms, amenities, and nearby attractions",
    demo: "https://react-kefkhw.stackblitz.io/",
    code: "https://github.com/saladilakshman/Beach-resort-app",
  },
];
